//auth Action Types
// register
export const ADD_FACULTY_FAIL = "ADD_FACULTY_FAIL";
export const ADD_ADMIN_FAIL = "ADD_ADMIN_FAIL";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";
export const ADD_SUBJECT_FAIL = "ADD_SUBJECT_FAIL";
export const FETCH_SUBJECT_FAIL = "FETCH_SUBJECT_FAIL";
export const FETCH_SUBJECT_SUCCESS = "FETCH_SUBJECT_SUCCESS";
export const FETCH_FACULTY_FAIL = "FETCH_FACULTY_FAIL";
export const FETCH_FACULTY_SUCCESS = "FETCH_FACULTY_SUCCESS";
