export const FETCH_ASSIGNED_SUBJECTS_SUCCESS =
  "FETCH_ASSIGNED_SUBJECTS_SUCCESS";
export const FETCH_ASSIGNED_SUBJECTS_FAIL = "FETCH_ASSIGNED_SUBJECTS_FAIL";
export const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS";
export const FETCH_STUDENT_FAIL = "FETCH_STUDENT_FAIL";
export const MARK_ATTENDANCE_FAIL = "MARK_ATTENDANCE_FAIL";
export const UPLOAD_MARKS_FAIL = "UPLOAD_MARKS_FAIL";
